module.exports = [
  { colorKey: 'd', id: 0, name: 'Black', rgb: '#000000' },
  { colorKey: 'w', id: 1, name: 'White', rgb: '#ffffff' },
  { colorKey: 's', id: 2, name: 'Slate', rgb: '#808080' },
  { colorKey: 'o', id: 3, name: 'Orange', rgb: '#ee8732' },
  { colorKey: 'r', id: 4, name: 'Red', rgb: '#b02418' },
  { colorKey: 'g', id: 5, name: 'Green', rgb: '#377e46' },
  { colorKey: 'b', id: 6, name: 'Blue', rgb: '#183ff5' },
  { colorKey: 'u', id: 7, name: 'Umber', rgb: '#774314' },
  { colorKey: 'D', id: 8, name: 'Light Dark', rgb: '#606060' },
  { colorKey: 'W', id: 9, name: 'Light Slate', rgb: '#c0c0c0' },
  { colorKey: 'P', id: 10, name: 'Light Purple', rgb: '#ea33f7' },
  { colorKey: 'y', id: 11, name: 'yellow', rgb: '#ffff54' },
  { colorKey: 'R', id: 12, name: 'Light Red', rgb: '#eb514a' },
  { colorKey: 'G', id: 13, name: 'Light Green', rgb: '#75fc4c' },
  { colorKey: 'B', id: 14, name: 'Light Blue', rgb: '#75fcfd' },
  { colorKey: 'U', id: 15, name: 'Light Umber', rgb: '#b7834c' },
  { colorKey: 'p', id: 16, name: 'Purple', rgb: '#83188b' },
  { colorKey: 'v', id: 17, name: 'Violet', rgb: '#842af6' },
  { colorKey: 't', id: 18, name: 'Teal', rgb: '#469e9f' },
  { colorKey: 'm', id: 19, name: 'Mud', rgb: '#6c6c38' },
  { colorKey: 'Y', id: 20, name: 'Light Yellow', rgb: '#ffff9f' },
  { colorKey: 'i', id: 21, name: 'Magenta-Pink', rgb: '#ea339d' },
  { colorKey: 'T', id: 22, name: 'Light Teal', rgb: '#79fcdd' },
  { colorKey: 'V', id: 23, name: 'Light Violet', rgb: '#b6a8f9' },
  { colorKey: 'I', id: 24, name: 'Light Pink', rgb: '#ef8783' },
  { colorKey: 'M', id: 25, name: 'Mustard', rgb: '#b4b439' },
  { colorKey: 'z', id: 26, name: 'Blue Slate', rgb: '#a6bfce' },
  { colorKey: 'Z', id: 27, name: 'Deep Light Blue', rgb: '#4fadf9' }
]
