// list-object-flags.h
export enum OF {
  SUST_STR,
  SUST_INT,
  SUST_WIS,
  SUST_DEX,
  SUST_CON,
  PROT_FEAR,
  PROT_BLIND,
  PROT_CONF,
  PROT_STUN,
  SLOW_DIGEST,
  FEATHER,
  REGEN,
  TELEPATHY,
  SEE_INVIS,
  FREE_ACT,
  HOLD_LIFE,
  IMPACT,
  BLESSED,
  BURNS_OUT,
  TAKES_FUEL,
  NO_FUEL,
  IMPAIR_HP,
  IMPAIR_MANA,
  AFRAID,
  NO_TELEPORT,
  AGGRAVATE,
  DRAIN_EXP,
  STICKY,
  FRAGILE,
  LIGHT_2,
  LIGHT_3,
  DIG_1,
  DIG_2,
  DIG_3,
  EXPLODE,
  TRAP_IMMUNE,
  THROWING,
  MULTIPLY_WEIGHT
}

export const OF_PROPS = {
  [OF.SUST_STR]: ' sStr',
  [OF.SUST_INT]: ' sInt',
  [OF.SUST_WIS]: ' sWis',
  [OF.SUST_DEX]: ' sDex',
  [OF.SUST_CON]: ' sCon',
  [OF.PROT_FEAR]: 'pFear',
  [OF.PROT_BLIND]: 'pBlnd',
  [OF.PROT_CONF]: 'pConf',
  [OF.PROT_STUN]: 'pStun',
  [OF.SLOW_DIGEST]: 'S.Dig',
  [OF.FEATHER]: 'Feath',
  [OF.REGEN]: 'Regen',
  [OF.TELEPATHY]: '  ESP',
  [OF.SEE_INVIS]: 'S.Inv',
  [OF.FREE_ACT]: 'FrAct',
  [OF.HOLD_LIFE]: 'HLife',
  [OF.IMPACT]: 'Impct',
  [OF.BLESSED]: ' Bless',
  [OF.BURNS_OUT]: 'BuOut',
  [OF.TAKES_FUEL]: 'TFuel',
  [OF.NO_FUEL]: 'NFuel',
  [OF.IMPAIR_HP]: 'ImpHP',
  [OF.IMPAIR_MANA]: 'ImpSP',
  [OF.AFRAID]: ' Fear',
  [OF.NO_TELEPORT]: 'NoTel',
  [OF.AGGRAVATE]: 'Aggrv',
  [OF.DRAIN_EXP]: 'DrExp',
  [OF.STICKY]: 'Stick',
  [OF.FRAGILE]: 'Fragl',
  [OF.LIGHT_2]: 'Lght2',
  [OF.LIGHT_3]: 'Lght3',
  [OF.DIG_1]: ' Dig1',
  [OF.DIG_2]: ' Dig2',
  [OF.DIG_3]: ' Dig3',
  [OF.EXPLODE]: 'Expld',
  [OF.TRAP_IMMUNE]: 'TrpIm',
  [OF.THROWING]: 'Throw',
  [OF.MULTIPLY_WEIGHT]: 'MulWg',
}
