// list-randart-properties.h
// Random artifact generation flags
export enum ART_IDX {
  BOW_SHOTS,
  BOW_MIGHT,
  BOW_BRAND,
  BOW_SLAY,
  WEAPON_HIT,
  WEAPON_DAM,
  NONWEAPON_HIT,
  NONWEAPON_DAM,
  NONWEAPON_HIT_DAM,
  NONWEAPON_BRAND,
  NONWEAPON_SLAY,
  NONWEAPON_BLOWS,
  NONWEAPON_SHOTS,
  MELEE_BLESS,
  MELEE_BRAND,
  MELEE_SLAY,
  MELEE_SINV,
  MELEE_BLOWS,
  MELEE_AC,
  MELEE_DICE,
  MELEE_WEIGHT,
  MELEE_TUNN,
  ALLARMOR_WEIGHT,
  BOOT_AC,
  BOOT_FEATHER,
  BOOT_STEALTH,
  BOOT_TRAP_IMM,
  BOOT_SPEED,
  BOOT_MOVES,
  GLOVE_AC,
  GLOVE_FA,
  GLOVE_DEX,
  GLOVE_HIT_DAM,
  HELM_AC,
  HELM_RBLIND,
  HELM_ESP,
  HELM_SINV,
  HELM_WIS,
  HELM_INT,
  SHIELD_AC,
  SHIELD_LRES,
  CLOAK_AC,
  CLOAK_STEALTH,
  ARMOR_AC,
  ARMOR_STEALTH,
  ARMOR_HLIFE,
  ARMOR_CON,
  ARMOR_LRES,
  ARMOR_ALLRES,
  ARMOR_HRES,
  GEN_STAT,
  GEN_SUST,
  GEN_STEALTH,
  GEN_SEARCH,
  GEN_INFRA,
  GEN_SPEED,
  GEN_IMMUNE,
  GEN_FA,
  GEN_HLIFE,
  GEN_FEATHER,
  GEN_LIGHT,
  GEN_SINV,
  GEN_ESP,
  GEN_SDIG,
  GEN_REGEN,
  GEN_LRES,
  GEN_RPOIS,
  GEN_RFEAR,
  GEN_RLIGHT,
  GEN_RDARK,
  GEN_RBLIND,
  GEN_RCONF,
  GEN_RSOUND,
  GEN_RSHARD,
  GEN_RNEXUS,
  GEN_RNETHER,
  GEN_RCHAOS,
  GEN_RDISEN,
  GEN_AC,
  GEN_TUNN,
  GEN_ACTIV,
  GEN_PSTUN,
  GEN_DAM_RED,
  GEN_MOVES,
  GEN_TRAP_IMM,
  WEAPON_AGGR,
  NONWEAPON_AGGR,
  MELEE_DICE_SUPER,
  BOW_SHOTS_SUPER,
  BOW_MIGHT_SUPER,
  GEN_SPEED_SUPER,
  MELEE_BLOWS_SUPER,
  MELEE_AC_SUPER,
  GEN_AC_SUPER
}

const artIdxBow = [
  ART_IDX.BOW_SHOTS,
  ART_IDX.BOW_MIGHT,
  ART_IDX.BOW_BRAND,
  ART_IDX.BOW_SLAY
]

const artIdxWeapon = [
  ART_IDX.WEAPON_HIT,
  ART_IDX.WEAPON_DAM,
  ART_IDX.WEAPON_AGGR
]

const artIdxNonWeapon = [
  ART_IDX.NONWEAPON_HIT,
  ART_IDX.NONWEAPON_DAM,
  ART_IDX.NONWEAPON_HIT_DAM,
  ART_IDX.NONWEAPON_AGGR,
  ART_IDX.NONWEAPON_BRAND,
  ART_IDX.NONWEAPON_SLAY,
  ART_IDX.NONWEAPON_BLOWS,
  ART_IDX.NONWEAPON_SHOTS
]

const artIdxMelee = [
  ART_IDX.MELEE_BLESS,
  ART_IDX.MELEE_SINV,
  ART_IDX.MELEE_BRAND,
  ART_IDX.MELEE_SLAY,
  ART_IDX.MELEE_BLOWS,
  ART_IDX.MELEE_AC,
  ART_IDX.MELEE_DICE,
  ART_IDX.MELEE_WEIGHT,
  ART_IDX.MELEE_TUNN
]

const artIdxAllArmor = [
  ART_IDX.ALLARMOR_WEIGHT
]

const artIdxBoot = [
  ART_IDX.BOOT_AC,
  ART_IDX.BOOT_FEATHER,
  ART_IDX.BOOT_STEALTH,
  ART_IDX.BOOT_TRAP_IMM,
  ART_IDX.BOOT_SPEED,
  ART_IDX.BOOT_MOVES
]

const artIdxGlove = [
  ART_IDX.GLOVE_AC,
  ART_IDX.GLOVE_HIT_DAM,
  ART_IDX.GLOVE_FA,
  ART_IDX.GLOVE_DEX
]

const artIdxHeadgear = [
  ART_IDX.HELM_AC,
  ART_IDX.HELM_RBLIND,
  ART_IDX.HELM_ESP,
  ART_IDX.HELM_SINV,
  ART_IDX.HELM_WIS,
  ART_IDX.HELM_INT
]

const artIdxShield = [
  ART_IDX.SHIELD_AC,
  ART_IDX.SHIELD_LRES
]

const artIdxCloak = [
  ART_IDX.CLOAK_AC,
  ART_IDX.CLOAK_STEALTH
]

const artIdxArmor = [
  ART_IDX.ARMOR_AC,
  ART_IDX.ARMOR_STEALTH,
  ART_IDX.ARMOR_HLIFE,
  ART_IDX.ARMOR_CON,
  ART_IDX.ARMOR_LRES,
  ART_IDX.ARMOR_ALLRES,
  ART_IDX.ARMOR_HRES
]

const artIdxGeneral = [
  ART_IDX.GEN_STAT,
  ART_IDX.GEN_SUST,
  ART_IDX.GEN_STEALTH,
  ART_IDX.GEN_SEARCH,
  ART_IDX.GEN_INFRA,
  ART_IDX.GEN_SPEED,
  ART_IDX.GEN_IMMUNE,
  ART_IDX.GEN_FA,
  ART_IDX.GEN_HLIFE,
  ART_IDX.GEN_FEATHER,
  ART_IDX.GEN_LIGHT,
  ART_IDX.GEN_SINV,
  ART_IDX.GEN_ESP,
  ART_IDX.GEN_SDIG,
  ART_IDX.GEN_REGEN,
  ART_IDX.GEN_LRES,
  ART_IDX.GEN_RPOIS,
  ART_IDX.GEN_RFEAR,
  ART_IDX.GEN_RLIGHT,
  ART_IDX.GEN_RDARK,
  ART_IDX.GEN_RBLIND,
  ART_IDX.GEN_RCONF,
  ART_IDX.GEN_RSOUND,
  ART_IDX.GEN_RSHARD,
  ART_IDX.GEN_RNEXUS,
  ART_IDX.GEN_RNETHER,
  ART_IDX.GEN_RCHAOS,
  ART_IDX.GEN_RDISEN,
  ART_IDX.GEN_AC,
  ART_IDX.GEN_TUNN,
  ART_IDX.GEN_ACTIV,
  ART_IDX.GEN_PSTUN,
  ART_IDX.GEN_DAM_RED,
  ART_IDX.GEN_MOVES,
  ART_IDX.GEN_TRAP_IMM
]

const artIdxHighResist = [
  ART_IDX.GEN_RPOIS,
  ART_IDX.GEN_RFEAR,
  ART_IDX.GEN_RLIGHT,
  ART_IDX.GEN_RDARK,
  ART_IDX.GEN_RBLIND,
  ART_IDX.GEN_RCONF,
  ART_IDX.GEN_RSOUND,
  ART_IDX.GEN_RSHARD,
  ART_IDX.GEN_RNEXUS,
  ART_IDX.GEN_RNETHER,
  ART_IDX.GEN_RCHAOS,
  ART_IDX.GEN_RDISEN,
  ART_IDX.GEN_PSTUN
]
