// list-tvals.h
// Type values; object base types
export enum TV {
  NULL,
  CHEST,
  SHOT,
  ARROW,
  BOLT,
  BOW,
  DIGGING,
  HAFTED,
  POLEARM,
  SWORD,
  BOOTS,
  GLOVES,
  HELM,
  CROWN,
  SHIELD,
  CLOAK,
  SOFT_ARMOR,
  HARD_ARMOR,
  DRAG_ARMOR,
  LIGHT,
  AMULET,
  RING,
  STAFF,
  WAND,
  ROD,
  SCROLL,
  POTION,
  FLASK,
  FOOD,
  MUSHROOM,
  MAGIC_BOOK,
  PRAYER_BOOK,
  NATURE_BOOK,
  SHADOW_BOOK,
  OTHER_BOOK,
  GOLD,
}

export const TV_NAMES: Record<string, TV> = {
  'none': TV.NULL,
  'chest': TV.CHEST,
  'shot': TV.SHOT,
  'arrow': TV.ARROW,
  'bolt': TV.BOLT,
  'bow': TV.BOW,
  'digger': TV.DIGGING,
  'hafted': TV.HAFTED,
  'polearm': TV.POLEARM,
  'sword': TV.SWORD,
  'boots': TV.BOOTS,
  'gloves': TV.GLOVES,
  'helm': TV.HELM,
  'crown': TV.CROWN,
  'shield': TV.SHIELD,
  'cloak': TV.CLOAK,
  'soft armor': TV.SOFT_ARMOR,
  'hard armor': TV.HARD_ARMOR,
  'dragon armor': TV.DRAG_ARMOR,
  'light': TV.LIGHT,
  'amulet': TV.AMULET,
  'ring': TV.RING,
  'staff': TV.STAFF,
  'wand': TV.WAND,
  'rod': TV.ROD,
  'scroll': TV.SCROLL,
  'potion': TV.POTION,
  'flask': TV.FLASK,
  'food': TV.FOOD,
  'mushroom': TV.MUSHROOM,
  'magic book': TV.MAGIC_BOOK,
  'prayer book': TV.PRAYER_BOOK,
  'nature book': TV.NATURE_BOOK,
  'shadow book': TV.SHADOW_BOOK,
  'other book': TV.OTHER_BOOK,
  'gold': TV.GOLD,
}
