// list-square-flags.h
enum SQUARE {
  NONE,
  MARK,
  GLOW,
  VAULT,
  ROOM,
  SEEN,
  VIEW,
  WASSEEN,
  FEEL,
  TRAP,
  INVIS,
  WALL_INNER,
  WALL_OUTER,
  WALL_SOLID,
  MON_RESTRICT,
  NO_TELEPORT,
  NO_MAP,
  NO_ESP,
  PROJECT,
  DTRAP,
  NO_STAIRS,
  CLOSE_PLAYER,
}

const SQUARE_DESCRIPTIONS = {
  [SQUARE.NONE]: '',
  [SQUARE.MARK]: 'memorized feature',
  [SQUARE.GLOW]: 'self-illuminating',
  [SQUARE.VAULT]: 'part of a vault',
  [SQUARE.ROOM]: 'part of a room',
  [SQUARE.SEEN]: 'seen flag',
  [SQUARE.VIEW]: 'view flag',
  [SQUARE.WASSEEN]: 'previously seen (during update)',
  [SQUARE.FEEL]: 'hidden points to trigger feelings',
  [SQUARE.TRAP]: 'square containing a known trap',
  [SQUARE.INVIS]: 'square containing an unknown trap',
  [SQUARE.WALL_INNER]: 'inner wall generation flag',
  [SQUARE.WALL_OUTER]: 'outer wall generation flag',
  [SQUARE.WALL_SOLID]: 'solid wall generation flag',
  [SQUARE.MON_RESTRICT]: 'no random monster flag',
  [SQUARE.NO_TELEPORT]: 'player can\'t teleport from this square',
  [SQUARE.NO_MAP]: 'square can\'t be magically mapped',
  [SQUARE.NO_ESP]: 'telepathy doesn\'t work on this square',
  [SQUARE.PROJECT]: 'marked for projection processing',
  [SQUARE.DTRAP]: 'trap detected square',
  [SQUARE.NO_STAIRS]: 'square is not suitable for placing stairs',
  [SQUARE.CLOSE_PLAYER]: 'square is seen and in player\'s light radius or UNLIGHT detection radius',
}
